name: Auto Assign

on:
  workflow_call:
    inputs:
      assignees:
        description: "The users to assign to the issue (separated by commas)"
        required: true
        type: string
      numOfAssignee:
        description: "The number of assignees to add"
        required: true
        type: number
    secrets:
      GITHUB_TOKEN:
        description: "GitHub token for authentication"
        required: true

jobs:
  auto-assign:
    name: Auto Assign
    runs-on: ubuntu-latest

    permissions:
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ inputs.assignees }}
          numOfAssignee: ${{ inputs.numOfAssignee }}
